### ISSUE TITLE
Tried to serve up '/config/www/community/calendar-card/calendar-card.js.map' but it does not exist

### ISSUE THREAD

**Issue by pergolafabio** [ljmerza/calendar-card#92]
what does the error below mean? it happens when i do a refresh of the lovelace page

2020-03-31 19:10:47 ERROR (MainThread) [hacs] Tried to serve up '/config/www/community/calendar-card/calendar-card.js.map' but it does not exist

Map.js:1104 Uncaught (in promise) Error: Map container is already initialized.
    at i._initContainer (Map.js:1104)
    at initialize (Map.js:136)
    at new i (Class.js:22)
    at Module.<anonymous> (Map.js:1717)
    at r (setup-leaflet-map.ts:25)
    at async HTMLElement.value (hui-map-card.ts:238)

**Comment by ljmerza** [comment]
fixed in v3.108.5

**Comment by pergolafabio** [comment]
that was quick :)

**Comment by LEJOUI** [comment]
This error still occurs in HA Core 0.108b2 and calendar-card 3.108.5

`Logger: hacs
Source: custom_components/hacs/http.py:76
First occurred: 17:28:17 (1 occurrences)
Last logged: 17:28:17

Tried to serve up '/config/www/community/calendar-card/dist/calendar-card.js' but it does not exist`

**Comment by pergolafabio** [comment]
For me it works on 107.7
